name: Copy Project

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
    - name: Create Token
      id: create-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.PEM }}
        owner: si-sa-a3
        repositories: test3
    - name: Authenticate with CLI
      run: |
        echo "${{ steps.create-token.outputs.token }}" | gh auth login --with-token
    - name: Create Token
      id: create-token2
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.A2_APP_ID }}
        private-key: ${{ secrets.A2_PEM }}
        owner: si-sa-a2
        repositories: test2
    - name: Authenticate with CLI
      run: |
        echo "${{ steps.create-token2.outputs.token }}" | gh auth login --with-token
    - name: Copy Project
      run: |
        gh project copy PVT_kwDOCqLjF84AmQI0 --source-owner si-sa-a3 --target-owner si-sa-a2 --title "copy Project"
