name: Copy Project2

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
    - name: Create Token
      id: create-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.PEM }}
        owner: si-sa-a3
        repositories: test3
        
    - name: Authenticate with CLI
      run: |
        echo "${{ steps.create-token.outputs.token }}" | gh auth login --with-token

    - name: Copy GitHub Project
      run: |
        gh api graphql -f query='
        query {
          organization(login: "si-sa-a3") {
            projectsV2(first: 10) {
              nodes {
                id
                number
                title
              }
            }
          }
        }' > projects.json
        cat projects.json

        # Extract the project ID for the specific project number
        project_id=$(jq -r '.data.organization.projectsV2.nodes[] | select(.number == 4) | .id' projects.json)
        echo "project_id=$project_id" >> $GITHUB_ENV

    - name: Get Project Fields
      run: |
        gh api graphql -f query='
        query {
          node(id: "'${{ env.project_id }}'") {
            ... on ProjectV2 {
              title
              fields(first: 100) {
                nodes {
                  ... on ProjectV2FieldCommon {
                    name
                    dataType
                  }
                  ... on ProjectV2SingleSelectField {
                    name
                    dataType
                  }
                  ... on ProjectV2IterationField {
                    name
                    dataType
                  }
                }
              }
            }
          }
        }' > project_fields.json
        cat project_fields.json

        # Extract title and fields
        title=$(jq -r '.data.node.title' project_fields.json)
        fields=$(jq -c '.data.node.fields.nodes')
        echo "title=$title" >> $GITHUB_ENV
        echo "fields=$fields" >> $GITHUB_ENV

    - name: Create Token
      id: create-token2
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.A2_APP_ID }}
        private-key: ${{ secrets.A2_PEM }}
        owner: si-sa-a2
        repositories: test2

    - name: Authenticate with CLI
      run: |
        echo "${{ steps.create-token2.outputs.token }}" | gh auth login --with-token

    - name: Create new project
      run: |
        gh api graphql -f query='
        mutation {
          createProjectV2(input: {ownerId: "si-sa-a2", title: "'${{ env.title }}'"}) {
            projectV2 {
              id
            }
          }
        }' > new_project.json
        cat new_project.json

        new_project_id=$(jq -r '.data.createProjectV2.projectV2.id' new_project.json)
        echo "new_project_id=$new_project_id" >> $GITHUB_ENV

    - name: Add fields to new project
      run: |
        fields=$(echo '${{ env.fields }}' | jq -c '.[]')
        for field in $fields; do
          name=$(echo $field | jq -r '.name')
          dataType=$(echo $field | jq -r '.dataType')
          # Add field creation logic here, as gh CLI does not support field creation directly
          echo "Field: $name, Type: $dataType"
        done