name: Copy Project2

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
    - name: Create Token
      id: create-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.PEM }}
        owner: si-sa-a3
        repositories: test3
        
    - name: Authenticate with CLI
      run: |
        echo "${{ steps.create-token.outputs.token }}" | gh auth login --with-token

    - name: Copy GitHub Project
      run: |
        gh api graphql -f query='
        query{
          organization(login: "si-sa-a3") {
            projectsV2(first: 10) {
              nodes {
                id
                number
                title
              }
            }
          }
        }' > projects.json
        cat projects.json

        # Extract the project ID for the specific project number
        project_id=$(jq -r '.data.organization.projectsV2.nodes[] | select(.number == 4) | .id' projects.json)
        echo "project_id=$project_id" >> $GITHUB_ENV

    - name: Get Project Fields
      run: |
        gh api graphql -f query='
        query {
          node(id: "'${{ env.project_id }}'") {
            ... on ProjectV2 {
              title
              fields(first: 100) {
                nodes {
                  ... on ProjectV2FieldCommon {
                    name
                    dataType
                  }
                  ... on ProjectV2SingleSelectField {
                    name
                    dataType
                  }
                  ... on ProjectV2IterationField {
                    name
                    dataType
                  }
                }
              }
            }
          }
        }' > project_fields.json
        cat project_fields.json
